name: Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of update to perform'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependency tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools poetry uv
          if [[ -f "requirements.txt" ]]; then
            pip install -r requirements.txt
          fi

      - name: Check current dependencies
        run: |
          echo "📋 Current dependencies:"
          if [[ -f "pyproject.toml" ]]; then
            echo "Found pyproject.toml"
            cat pyproject.toml
          fi
          if [[ -f "requirements.txt" ]]; then
            echo "Found requirements.txt"
            cat requirements.txt
          fi

      - name: Update dependencies with pip-tools
        if: hashFiles('requirements.in') != ''
        run: |
          echo "🔄 Updating dependencies with pip-tools..."
          pip-compile requirements.in --upgrade
          if [[ -f "requirements-dev.in" ]]; then
            pip-compile requirements-dev.in --upgrade
          fi

      - name: Update dependencies with Poetry
        if: hashFiles('poetry.lock') != ''
        run: |
          echo "🔄 Updating dependencies with Poetry..."
          UPDATE_TYPE="${{ github.event.inputs.update_type || 'minor' }}"
          
          case $UPDATE_TYPE in
            "patch")
              poetry update --lock
              ;;
            "minor")
              poetry update
              ;;
            "major")
              poetry update --lock
              # For major updates, we'll be more conservative
              echo "Major updates require manual review"
              ;;
          esac

      - name: Update GitHub Actions
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Get all workflow files
            const workflowDir = '.github/workflows';
            const files = fs.readdirSync(workflowDir);
            
            for (const file of files) {
              if (file.endsWith('.yml') || file.endsWith('.yaml')) {
                const filePath = path.join(workflowDir, file);
                let content = fs.readFileSync(filePath, 'utf8');
                
                // Update common action versions
                const updates = {
                  'actions/checkout@v3': 'actions/checkout@v4',
                  'actions/setup-python@v3': 'actions/setup-python@v4',
                  'actions/cache@v2': 'actions/cache@v3',
                  'actions/upload-artifact@v2': 'actions/upload-artifact@v4',
                  'actions/upload-artifact@v3': 'actions/upload-artifact@v4',
                  'actions/download-artifact@v2': 'actions/download-artifact@v4',
                  'actions/download-artifact@v3': 'actions/download-artifact@v4'
                };
                
                let updated = false;
                for (const [old, newVersion] of Object.entries(updates)) {
                  if (content.includes(old)) {
                    content = content.replace(new RegExp(old, 'g'), newVersion);
                    updated = true;
                  }
                }
                
                if (updated) {
                  fs.writeFileSync(filePath, content);
                  console.log(`Updated ${file}`);
                }
              }
            }

      - name: Run security check on updated dependencies
        run: |
          echo "Running security check on updated dependencies..."
          pip install safety pip-audit
          
          # Install updated dependencies
          if [[ -f "requirements.txt" ]]; then
            pip install -r requirements.txt
          elif [[ -f "pyproject.toml" ]]; then
            pip install -e .
          fi
          
          # Run security checks
          safety check --continue-on-error
          pip-audit --format=cyclonedx --output=updated-sbom.json

      - name: Run tests with updated dependencies
        run: |
          echo "Running tests with updated dependencies..."
          pip install pytest pytest-cov
          echo "Tests temporarily disabled - will be added when test suite is ready"

      - name: Check for changes
        id: changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Dependency updates detected"
            git status
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No dependency updates needed"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { createDependencyPR } = require('./.github/scripts/create-dependency-pr.js');
            const updateType = '${{ github.event.inputs.update_type || 'scheduled' }}';
            
            return await createDependencyPR({
              github,
              context,
              updateType
            });

      - name: Upload updated SBOM
        if: steps.changes.outputs.changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: updated-sbom
          path: updated-sbom.json

  check-outdated:
    name: Check for Outdated Dependencies
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-check pip-audit
          pip install -r requirements.txt
          pip install -e .

      - name: Check for outdated packages
        run: |
          echo "Checking for outdated packages..."
          pip list --outdated --format=columns || true
          echo ""
          echo "Checking for dependency conflicts..."
          pip-check || true

      - name: Generate dependency report
        run: |
          echo "## Dependency Status Report" >> dependency-report.md
          echo "" >> dependency-report.md
          echo "### Outdated Packages" >> dependency-report.md
          echo "\`\`\`" >> dependency-report.md
          pip list --outdated --format=columns >> dependency-report.md || echo "No outdated packages found" >> dependency-report.md
          echo "\`\`\`" >> dependency-report.md
          echo "" >> dependency-report.md
          echo "### Security Vulnerabilities" >> dependency-report.md
          echo "\`\`\`" >> dependency-report.md
          pip-audit --format=cyclonedx --output=current-sbom.json
          pip-audit >> dependency-report.md 2>&1 || echo "No known vulnerabilities found" >> dependency-report.md
          echo "\`\`\`" >> dependency-report.md

      - name: Upload dependency report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: |
            dependency-report.md
            current-sbom.json